apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: user
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001